### ISSUE TITLE
BetterJapanese.user.jsの公開時にコメントが消えている

### ISSUE THREAD

**Issue by LPerNATTO** [hideki0403/better-japanese#50]
src/web/BetterJapanese.user.jsでは存在しているファイル先頭のコメントが公開URLのファイルにおいては消失しております。
そのためTampermonkeyで読み込んだときにメタデータが存在しないとして読み込めない状況になっております。

**Comment by hideki0403** [comment]
Cloudflareのautominifyが原因でコメントが消されてしまっていました...
現在は修正済みです..！
