### ISSUE TITLE
オフライン中に生産したクッキーの獲得メッセージがおかしい

### ISSUE THREAD

**Issue by kaz-mighty** [hideki0403/better-japanese#89]
指数表記の時、先頭1桁の数字しか表示されません。

これもおそらくweb版限定?

**Comment by hideki0403** [comment]
すみません、こちらの問題について自身の環境では同様の症状が発生しないのですが、スクリーンショット等などありますでしょうか...？
もし可能であれば、設定タブのスクリーンショットと合わせて対象のメッセージのスクリーンショットも添付して頂けると助かります...！

**Comment by kaz-mighty** [comment]
スクリーンショットを取りました。
![スクリーンショット 2023-01-14 214945](https://user-images.githubusercontent.com/57952859/212472742-ef94f932-6410-47cd-8b71-14a65b79bada.png)

**Comment by hideki0403** [comment]
ありがとうございます！
