### ISSUE TITLE
単位設定変更時の既存要素に対する変更適用処理が不十分

### ISSUE THREAD

**Issue by LPerNATTO** [hideki0403/better-japanese#94]
現在の単位変更時の処理はカンマ区切りの10進数表示のみ再度変換し直すようになっています(BeautifyInTextの正規表現で検索し置換する)。
しかし、一部アップグレードや実績(Just plain lucky(ただのラッキー))などは元々の説明が英語単位や日本語単位で初期化されるため、再翻訳処理が働かないという不具合があります。
そのため、BeautifyInTextの正規表現か初期化処理などを修正する必要があると思われます。
(以前対応したような記憶がありますが、まだ未対応の用件でしたら対応したいと考えております。)

**Comment by hideki0403** [comment]
すみません、認識に相違があるといけないので確認したいのですが、この問題の対象となるプラットフォームはSteam版でしょうか...？

Web版だと問題を再現出来なかった（日本語単位に翻訳されていた）のでプラットフォームがSteam版であることを仮定しての解決案ですが、現状のModの初期化順序が

① lang.jsを読み込んで既存の日本語翻訳を上書きする
② CookieClicker本体による実績等の定義 (この段階でBeautifyに通される)
③ main.jsを読み込んでBeautifyを上書きする

であることから、lang.js内でBeautifyを上書きすれば問題が解決するのではないかと思います。
> 追記: Game.registerModで呼び出しを待っている関係で③の処理が②よりも後に実行されていたようなので、実際はlang.js内でBeautifyを上書きしなくても大丈夫なようです


かなり大幅な変更になりそうなので、問題がなければ私の方で修正したく思うのですがいかがでしょうか...？

**Comment by LPerNATTO** [comment]
本件についてはWeb版でも確認しております。

おそらく問題点が誤って伝わってしまったと思われますので問題点について補足いたします。
本件は基本的には本家の挙動とは異なるため、問題点というよりは要望(Enhancement)？に近いと思われます。

Short numbersの設定を編集するとBeautifyAll関数が実行され、すべての実績とアップグレードの概要(ddesc)の数がBeautifyInText関数によって再整形されます。
したがって、現在の単位の設定によって概要の値(○○クッキー焼く、など)が設定に合わせた表示に変化するはずです。
ただし、このときの再整形はカンマ区切りの数のみ(単位がついた値は単位を含まない数値表記部のみ)を再整形します。
しかし、本家のままでは初期化時にddescに一度整形した後の値(Short numbersがオンなら単位あり)を格納するため、実際にはこの再整形はほとんど働きません。
(このような仕様から、短縮表記オフの状態で初期化して初期化終了後に短縮表記をオンにするケースのみにおいては、指数表記でない値は単位付きの値に再整形される、といった形で正常に動作します。逆は動作しません。)
これを正しく設定に合わせて変化するようにしたい、またShort numbersの設定だけでなくbetterJapaneseの日本語単位、塵劫記単位、第二単位の設定についても反映されるようにしたい、という要望になります。

上記の経緯から本件はこだわりの側面が強いため、対応についてはやっていただけるのであればお願いしたい、くらいの感じです。(修正の必要性があまり感じられないのであれば時間があるときにこちらでやるといった感じで…)

**Comment by hideki0403** [comment]
なるほど、承知しました。
確かにBeautifyInTextで日本語単位を含む数値→変更後の数値に変換するという処理を行うようにしても良いとは思うのですが、
- 日本語単位をパースして数値化: 華厳経単位, 塵劫記単位, 第二単位とパターンが多く、ソースコードの肥大化に繋がったりとメリットよりデメリットが大きい
- CookieClicker本体の関数を改造してAchievementオブジェクト等に生の数値を埋め込み、BeautifyInTextで生の数値をもとに数値を変換する: かなり良さそうな手段ではあるものの、 生の数値を埋め込む際にフックできそうな関数が(自身が調べた限りでは)存在しない

といった感じなので、いっそのこと単位変更を検知して「変更後の単位を全てに適用するには再読み込みをしてください」等のメッセージをダイアログ（または画面下部に通知）を出してあげるのがよいのではないかと感じました。
これが最適かと言われると必ずしもそうとは言い切れないのですが、解決策のひとつとしてどうでしょうか...？
